//
// NewsResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct NewsResponse: Codable {

    public var status: String?
    public var articles: [Article]?

    public init(status: String, articles: [Article]) {
        self.status = status
        self.articles = articles
    }

}
